---

- name: Install zsh
  apt: name="zsh"

- name: Clone oh-my-zsh repo
  git: repo=https://github.com/robbyrussell/oh-my-zsh.git dest=/home/{{ ansible_ssh_user }}/.oh-my-zsh

- name: Set zsh as default shell
  user: name={{ ansible_ssh_user }} shell=/bin/zsh

- name: Use default .zshrc
  command: cp /home/{{ ansible_ssh_user }}/.oh-my-zsh/templates/zshrc.zsh-template /home/{{ ansible_ssh_user }}/.zshrc

- name: "Switching to {{ ohmyzsh.theme }} theme"
  lineinfile: dest=/home/{{ ansible_ssh_user }}/.zshrc regexp=^ZSH_THEME line=ZSH_THEME="{{ ohmyzsh.theme }}"
